<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_On Now_mvpd-logo mr-4 mb-1</name>
   <tag></tag>
   <elementGuidId>7897f65f-1c95-406c-94ac-34f5447297d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.mvpd-logo.mr-4.mb-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>025a553a-bf73-4d62-aea6-124b60518f2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mvpd-logo mr-4 mb-1</value>
      <webElementGuid>3fcd3786-0abb-4680-8ccd-bf95e544db01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://d2qr3uxp73c4cw.cloudfront.net/logos/dark/optimum_dark.png</value>
      <webElementGuid>1336c352-e23d-435f-ba08-6b0fff3fbd49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>mvpd_logo</value>
      <webElementGuid>14d4df41-addb-4353-b36a-95006059e40d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;watch-page&quot;]/div[@class=&quot;player-container d-flex flex-column&quot;]/div[@class=&quot;watch-header d-flex align-items-center justify-content-between mb-2&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/img[@class=&quot;mvpd-logo mr-4 mb-1&quot;]</value>
      <webElementGuid>a2e862d5-e318-4435-8e31-89e2115ae87d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/div/img</value>
      <webElementGuid>fe4631db-a92f-4557-92e3-d8b6ff36b980</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='mvpd_logo']</value>
      <webElementGuid>8bebceb5-a724-44eb-8f70-04e27d82bd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>47a6d712-1fda-4cb1-b3dc-ab9e6825476e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://d2qr3uxp73c4cw.cloudfront.net/logos/dark/optimum_dark.png' and @alt = 'mvpd_logo']</value>
      <webElementGuid>c0e4f514-ab5e-4e26-9126-b13f8b8ce20c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
