<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_On Now_d-flex justify-content-between s_a34468</name>
   <tag></tag>
   <elementGuidId>f1406849-f287-4425-b1eb-de6a2ea8b1b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.d-flex.justify-content-between.search-section</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e7a966a6-4b7e-4b5e-ad02-9a48f6877f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-flex justify-content-between search-section</value>
      <webElementGuid>282b9a3c-6fa8-46f9-af28-af2e42b7da91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;watch-page&quot;]/div[@class=&quot;d-flex justify-content-between search-section&quot;]</value>
      <webElementGuid>e75b8dce-0a14-4e98-bc70-3933a69292f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div</value>
      <webElementGuid>4ecd9f6a-3419-485e-be00-2f5430c0f444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Now'])[1]/preceding::div[4]</value>
      <webElementGuid>7a4ca024-d218-4158-9e19-edcf06719a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUBSCRIBE NOW'])[1]/preceding::div[6]</value>
      <webElementGuid>be8e800b-72c3-49ec-8c9b-b2d6ea6d8cb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div</value>
      <webElementGuid>68a020b3-ede0-4398-ba95-122c731654a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
