<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_EmailPasswordForgot PasswordLOGINORCont_a24b9f</name>
   <tag></tag>
   <elementGuidId>bef73dec-4b7e-44f7-aede-b595c48eb23a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.auth__card-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[3]/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>e06c01ea-72ab-47e3-907a-a6132ad0d2ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth__card-body</value>
      <webElementGuid>cd001a32-0f4d-4ca5-b1b1-c104323189b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EmailPasswordForgot Password?LOGINORContinue with GoogleContinue with FacebookContinue with Apple</value>
      <webElementGuid>830b1dc5-7ae6-471d-9414-c68a39d25191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;page-background&quot;]/div[3]/div[@class=&quot;auth__card&quot;]/div[@class=&quot;auth__card-body&quot;]</value>
      <webElementGuid>3be1c6f7-94e5-40f5-b7d3-f4e3373b4e1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[3]/div/div</value>
      <webElementGuid>d2fc6213-5a69-4cf8-9e63-803b59e427de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A NEW YORK MINUTE'])[1]/following::div[3]</value>
      <webElementGuid>66ccd9b6-5aad-4121-afc0-91320a5b3a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGIN IN LESS THAN'])[1]/following::div[4]</value>
      <webElementGuid>dac33b89-716f-4432-b2e5-117222900da6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>bab15ba6-62e3-47f5-960b-34933fd0b56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'EmailPasswordForgot Password?LOGINORContinue with GoogleContinue with FacebookContinue with Apple' or . = 'EmailPasswordForgot Password?LOGINORContinue with GoogleContinue with FacebookContinue with Apple')]</value>
      <webElementGuid>61fd4955-8f3d-4afd-8f8c-77f9a22cc419</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
