<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Subscribe now for just 239.99yr or 24.99mo</name>
   <tag></tag>
   <elementGuidId>d52c7738-7b74-41fd-89a4-dc4f375ddc2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.subscriber_section_desc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f77aedc9-4a48-4d69-b18c-b7298471aa54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>subscriber_section_desc</value>
      <webElementGuid>787c7e21-ead4-4129-af58-cdbb001d3e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscribe now for just $239.99/yr or $24.99/mo</value>
      <webElementGuid>b34ea157-20e1-49c5-9de7-118ab35414cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;landing_page&quot;]/div[@class=&quot;login_section&quot;]/div[@class=&quot;subscribe_section&quot;]/div[@class=&quot;subscriber_section_desc&quot;]</value>
      <webElementGuid>256392d9-992c-4bf5-af89-efd3ee0b9606</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div</value>
      <webElementGuid>cdbd248a-980b-47de-9c6b-676609171bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGIN WITH YES APP ACCOUNT'])[1]/following::div[2]</value>
      <webElementGuid>438125fa-ea21-40fc-b860-c40f271f225b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LOGIN WITH TV PROVIDER'])[1]/following::div[3]</value>
      <webElementGuid>a29a6bee-3827-4098-9166-0851fe4502d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Introductory offer. Subject to territorial restrictions.'])[1]/preceding::div[1]</value>
      <webElementGuid>363b5a28-9d42-46f2-ad13-0b33d2973c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUBSCRIBE NOW'])[1]/preceding::div[2]</value>
      <webElementGuid>56de19b8-26f3-489a-881c-76e0b72767cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subscribe now for just $239.99/yr or $24.99/mo']/parent::*</value>
      <webElementGuid>ec0d21fa-9a1b-4367-8496-83b3ee5ed108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>3909915f-7db7-40fd-88ae-17f80f0e94ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Subscribe now for just $239.99/yr or $24.99/mo' or . = 'Subscribe now for just $239.99/yr or $24.99/mo')]</value>
      <webElementGuid>a4820972-4704-4b17-8ae8-5ee04bae7437</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
